---
functional:
  - Пользователь должен иметь возможность зарегестрироваться в системе
  - Можно выбрать игру по уровню сложности
  - При создании игры можно выбрать определенную игру
  - Пользователь может следить за ходом игры другого пользователя
  - Пользователь может использовать чат
  - Пользователь может просматривать запись игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Описание задач дано на двух языках — русском и английском
  - Редактор для ввода кода выглядит как проигрыватель
implicit:
  - Сайт должен поддерживать русский язык #направлен на русскоязычную аудиторию
  - Пользователь получает очки за проведенные игры
